ALTER TABLE cps DROP COLUMN IF EXISTS reason_off;

ALTER TABLE queue_lane DROP COLUMN IF EXISTS reason_off;

ALTER TABLE lanes DROP COLUMN IF EXISTS reason_off;

ALTER TABLE cps ADD COLUMN reason_off VARCHAR(255) NULL;

ALTER TABLE queue_lane ADD COLUMN reason_off VARCHAR(255) NULL;

ALTER TABLE lanes ADD COLUMN reason_off VARCHAR(255) NULL;
