ALTER TABLE cp_queue_assignments DISABLE TRIGGER cp_queue_assignments_trigger_changes;
ALTER TABLE cp_queue_assignments DISABLE TRIGGER trg_fsetdefault_nomorlambung;
ALTER TABLE cp_queue_assignments DISABLE TRIGGER before_insert_update_cp_queue;
ALTER TABLE cp_queue_assignments DISABLE TRIGGER after_cp_queue_assignment_change;
ALTER TABLE cp_queue_assignments DISABLE TRIGGER after_insert_update_cp_queue;
ALTER TABLE cp_queue_assignments DISABLE TRIGGER trg_validate_lane_capacity;
create type queue_status_enum as enum('IN-SB','WAITING','ASSIGNED_TO_CP_QUEUE','ASSIGNED_TO_CP','ARRIVED','COMPLETED');
alter table cp_queue_assignments add column  temp_status varchar(100);
update cp_queue_assignments set temp_status=status::text;
alter table cp_queue_assignments drop status cascade;
alter table cp_queue_assignments add column  status queue_status_enum;
update cp_queue_assignments set status=temp_status::queue_status_enum;
ALTER TABLE cp_queue_assignments ALTER COLUMN status SET DEFAULT 'IN-SB';
alter table cp_queue_assignments drop column temp_status; 
DROP TYPE queue_status_enum_new;
ALTER TABLE cp_queue_assignments ENABLE TRIGGER cp_queue_assignments_trigger_changes;
ALTER TABLE cp_queue_assignments ENABLE TRIGGER trg_fsetdefault_nomorlambung;
ALTER TABLE cp_queue_assignments ENABLE TRIGGER before_insert_update_cp_queue;
ALTER TABLE cp_queue_assignments ENABLE TRIGGER after_cp_queue_assignment_change;
ALTER TABLE cp_queue_assignments ENABLE TRIGGER after_insert_update_cp_queue;
ALTER TABLE cp_queue_assignments ENABLE TRIGGER trg_validate_lane_capacity;
