DROP TABLE IF EXISTS cp_tonages;
CREATE TABLE IF NOT EXISTS "cp_tonages" (
	"id" SERIAL PRIMARY KEY, 
	"cp_id" INTEGER NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"created_by" VARCHAR(100) NULL,
	"auditupdate" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" VARCHAR(100) NULL,
	"uid" VARCHAR(120) NULL,
	"connection" BOOLEAN NULL DEFAULT true,
	"item_name" VARCHAR(120) NULL,
	"item_id" VARCHAR(120) NULL,
	"value" INTEGER NULL DEFAULT 0
);
